package in.at.testannotation;

import org.openqa.selenium.*;
import org.openqa.selenium.interactions.Actions;
import org.sikuli.script.FindFailed;
import org.sikuli.script.Screen;

import java.util.List;

public class PlaynGoModels {
    WebDriver driver;
    Screen screen = new Screen();

    public PlaynGoModels(WebDriver driver) {
        this.driver = driver;
    }

    public  void  PLAYNGO() throws InterruptedException, FindFailed {
        Models model = new Models(driver);
        model.GoToCasino("PLAY'N GO");

        model.Scroll();
        Actions actions = new Actions(driver);
        String Balance = driver.findElements((By.cssSelector("#wallet>ul>li>span"))).get(0).getText();
        System.out.println(Balance);
        List<WebElement> count = driver.findElements(By.cssSelector(".games-name"));
        System.out.println(count.size()); //game count
        for (int i = 3; i <= count.size() + 2; i++) {
            String GameName = driver.findElements(By.cssSelector(".games-name")).get(i - 3).getAttribute("title");
            WebElement elem = driver.findElements((By.cssSelector(".all-casino-games-list-content>.all-games-container>a"))).get(i - 3);
            ((JavascriptExecutor) driver).executeScript("arguments[0].scrollIntoView(true);", elem);
            ((JavascriptExecutor) driver).executeScript("window.scrollBy(0,-100)");
            Thread.sleep(500);
            WebElement Play = driver.findElements(By.cssSelector(".games-buttons")).get(i).findElement(By.cssSelector("strong>button"));
            //WebElement Play = driver.findElements(By.cssSelector(".all-games-container")).get(1).findElements(By.cssSelector("a")).get(i).findElement(By.cssSelector(".games-buttons>strong>button")); //play now
            Thread.sleep(1000);
            try {
                actions.click(Play).perform();
            } catch (JavascriptException NewGame) {
                System.out.println("It's New Game  " + GameName + "   " + driver.getCurrentUrl());
                //commands.Click(StaticWebElements.Slote_X_icon);
                driver.navigate().back();

                i--;
                continue;
            }
            String GetUrlNum = "";
            int Num = 0;
            Thread.sleep(2000);
            try {
                GetUrlNum = driver.getCurrentUrl().replaceAll("\\D+", "");
                Num = Integer.parseInt(GetUrlNum);
            } catch (NumberFormatException e) {
                System.out.println("Mtela format exeption------------------------------------------------");
                actions.click(Play).perform();
                GetUrlNum = driver.getCurrentUrl().replaceAll("\\D+", "");
                Num = Integer.parseInt(GetUrlNum);
            }
            try {
                int GameNumber = i - 2;
                System.out.println("GameNumber  " + GameNumber);
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_5.png", Num, 23810, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_6.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_15.png", Num, 23496, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_16.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_1.png", Num, 3884, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_2.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_3.png", Num, 23301, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_4.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_7.png", Num, 23168, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_8.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_9.png", Num, 23037, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_10.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_11.png", Num, 22856, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_12.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_13.png", Num, 22603, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_14.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_17.png", Num, 22450, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_18.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_20.png", Num, 22102, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_21.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_19.png", Num, 22386, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_22.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_23.png", Num, 22100, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_24.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_25.png", Num, 21802, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_26.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_27.png", Num, 21984, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_28.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_29.png", Num, 21718, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_30.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_31.png", Num, 3834, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_32.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_33.png", Num, 9194, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_34.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_35.png", Num, 3824, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_36.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_37.png", Num, 18043, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_38.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_39.png", Num, 14953, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_40.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_41.png", Num, 17797, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_42.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_43.png", Num, 3842, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_44.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_45.png", Num, 9208, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_46.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_47.png", Num, 8530, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_48.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_49.png", Num, 9745, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_50.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_51.png", Num, 9788, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_52.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_53.png", Num, 20853, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_54.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_55.png", Num, 3825, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_56.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_57.png", Num, 14439, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_58.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_59.png", Num, 7203, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_60.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_61.png", Num, 14649, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_62.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_63.png", Num, 20046, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_64.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_65.png", Num, 14404, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_66.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_67.png", Num, 10450, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_68.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_71.png", Num, 3829, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_72.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_73.png", Num, 20850, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_74.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_75.png", Num, 18392, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_76.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_77.png", Num, 24095, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_78.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_79.png", Num, 3860, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_80.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_81.png", Num, 14853, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_82.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_83.png", Num, 3876, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_84.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_85.png", Num, 10800, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_86.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_87.png", Num, 3830, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_88.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_89.png", Num, 15696, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_90.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_91.png", Num, 3864, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_92.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_93.png", Num, 11634, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_94.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_95.png", Num, 15951, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_96.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_97.png", Num, 3853, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_98.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_99.png", Num, 20162, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_100.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_101.png", Num, 15043, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_102.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_103.png", Num, 14521, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_104.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_105.png", Num, 9628, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_106.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_107.png", Num, 3839, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_108.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_109.png", Num, 3872, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_110.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_111.png", Num, 3850, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_112.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_113.png", Num, 3836, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_114.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_115.png", Num, 3851, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_116.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_117.png", Num, 3874, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_118.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_119.png", Num, 21111, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_120.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_121.png", Num, 3882, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_122.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_123.png", Num, 13055, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_124.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_125.png", Num, 3831, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_126.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_127.png", Num, 24287, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_128.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_129.png", Num, 16151, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_130.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_131.png", Num, 3812, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_132.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_133.png", Num, 7197, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_134.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_135.png", Num, 12136, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_136.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_139.png", Num, 3827, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_140.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_141.png", Num, 9214, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_142.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_143.png", Num, 3845, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_144.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_145.png", Num, 19756, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_146.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_147.png", Num, 3886, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_148.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_149.png", Num, 10369, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_150.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_151.png", Num, 3828, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_152.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_153.png", Num, 3869, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_154.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_155.png", Num, 20610, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_156.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_157.png", Num, 3865, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_158.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_159.png", Num, 3879, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_160.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_161.png", Num, 9333, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_162.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_163.png", Num, 3881, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_164.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_165.png", Num, 21609, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_166.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_167.png", Num, 14495, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_168.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_169.png", Num, 9202, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_170.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_171.png", Num, 9226, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_172.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_173.png", Num, 8524, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_174.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_175.png", Num, 7201, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_176.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_177.png", Num, 13842, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_178.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_179.png", Num, 8522, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_180.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_183.png", Num, 13919, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_184.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_185.png", Num, 11832, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_186.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_187.png", Num, 3835, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_188.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_189.png", Num, 9228, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_190.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_191.png", Num, 3859, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_192.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_193.png", Num, 3852, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_194.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_195.png", Num, 9201, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_196.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_197.png", Num, 3841, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_198.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_201.png", Num, 20250, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_202.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_203.png", Num, 3811, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_204.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_205.png", Num, 3861, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_206.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_207.png", Num, 15449, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_208.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_209.png", Num, 8526, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_210.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_211.png", Num, 3847, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_212.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_213.png", Num, 15896, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_214.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_215.png", Num, 3620, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_216.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_217.png", Num, 11677, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_218.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_219.png", Num, 9193, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_220.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_221.png", Num, 3868, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_222.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_223.png", Num, 14038, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_224.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_225.png", Num, 9210, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_226.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_227.png", Num, 9206, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_228.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_229.png", Num, 9212, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_230.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_231.png", Num, 3863, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_232.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_233.png", Num, 3844, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_234.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_237.png", Num, 19534, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_238.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_239.png", Num, 20677, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_240.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_241.png", Num, 3840, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_242.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_243.png", Num, 12025, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_244.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_245.png", Num, 3862, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_246.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_247.png", Num, 11354, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_248.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_249.png", Num, 3832, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_250.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_251.png", Num, 3870, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_252.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_253.png", Num, 9217, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_254.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_255.png", Num, 9199, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_256.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_257.png", Num, 7193, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_258.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_259.png", Num, 10299, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_260.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_261.png", Num, 21479, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_262.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_263.png", Num, 3849, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_264.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_265.png", Num, 10021, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_266.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_267.png", Num, 19024, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_268.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_269.png", Num, 14270, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_270.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_271.png", Num, 19020, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_272.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_273.png", Num, 21185, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_274.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_275.png", Num, 7195, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_276.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_277.png", Num, 18635, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_278.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_279.png", Num, 3838, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_280.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_281.png", Num, 16736, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_282.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_283.png", Num, 19990, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_284.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_289.png", Num, 12216, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_290.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_293.png", Num, 3875, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_294.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_295.png", Num, 11698, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_296.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_297.png", Num, 3885, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_298.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_299.png", Num, 3880, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_300.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_301.png", Num, 20113, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_302.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_303.png", Num, 7199, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_304.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_305.png", Num, 9224, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_306.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_307.png", Num, 3833, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_308.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_309.png", Num, 3826, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_310.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_311.png", Num, 3871, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_312.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_313.png", Num, 9938, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_314.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_315.png", Num, 16814, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_316.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_317.png", Num, 9221, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_318.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_319.png", Num, 8532, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_320.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_321.png", Num, 19022, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_322.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_323.png", Num, 8528, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_324.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_325.png", Num, 20854, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_326.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_327.png", Num, 17492, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_328.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_329.png", Num, 16590, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_330.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_331.png", Num, 13238, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_332.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_333.png", Num, 12320, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_334.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_335.png", Num, 3867, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_336.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_337.png", Num, 19150, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_338.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_339.png", Num, 9175, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_340.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_341.png", Num, 18901, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_342.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_343.png", Num, 9190, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_344.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_345.png", Num, 15646, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_346.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_349.png", Num, 10189, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_350.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_351.png", Num, 15235, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_352.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_353.png", Num, 3619, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_354.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_355.png", Num, 3873, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_356.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_357.png", Num, 12994, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_358.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_359.png", Num, 15438, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_360.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_361.png", Num, 19877, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_362.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_363.png", Num, 3878, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_364.png");


                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_365.png", Num, 24566, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_366.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_367.png", Num, 25012, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_368.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_369.png", Num, 24885, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_370.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_371.png", Num, 24652, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_372.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_373.png", Num, 24511, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_374.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_375.png", Num, 13921, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_376.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_377.png", Num, 3813, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_378.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_379.png", Num, 19455, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_380.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_381.png", Num, 3866, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_382.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_383.png", Num, 9218, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_384.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_385.png", Num, 19919, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_386.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_387.png", Num, 3848, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_388.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_389.png", Num, 13718, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_390.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_391.png", Num, 17694, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_392.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_393.png", Num, 9222, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_394.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_395.png", Num, 3846, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_396.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_399.png", Num, 3883, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_400.png");
                model.GameImformWhenPath_2("C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_401.png", Num, 14743, GameName, "C:\\Users\\hambardzumyan.levon\\IdeaProjects\\VbetProviders\\src\\test\\PLaynGoImg\\Screenshot_402.png");
                if (Num==3815||Num==3814||Num==8607||Num==3854||Num==3621||Num==3816||Num==17490||Num==3806||Num==3817||Num==3819||Num==3887||Num==3820){
                    driver.navigate().back();
                }
            }catch (FindFailed e) {
                System.out.println(GameName + " - -  " + driver.getCurrentUrl());
                driver.navigate().back();
            }
        }
    }
}
